--CREATE DATABASE logto;
CREATE DATABASE crib;
CREATE DATABASE fixleakage;

CREATE USER crib_user WITH PASSWORD '5iIETsGbqAAlNxfsu7drcD7c';

CREATE USER fixleakage_user WITH PASSWORD '6SiMIVbJWKt1YvFx6pr2UTNv';

GRANT ALL PRIVILEGES ON DATABASE crib TO crib_user;
GRANT ALL PRIVILEGES ON DATABASE fixleakage TO fixleakage_user;